/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.westernunav1;

import java.util.ArrayList;
import javax.swing.JPanel;

import java.awt.*; 
import java.awt.image.*;
import java.awt.event.*;  
import java.io.File;
import java.lang.Exception;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author tanusri
 */
public class User extends javax.swing.JFrame {
    
    private String name; //UserName of the person
    private String loginCredentials; //Password of the person
    private ArrayList<PointofInterest> savedPOI; //Saved POI's associated with the user info

    /**
     * Creates new form User
     */
    public User() {
        initComponents();
    }
    
    public User(String name, String loginCredentials, ArrayList<PointofInterest> savedPOI) {
        this.name = name;
        this.loginCredentials = loginCredentials;
        this.savedPOI = savedPOI;
    }
    
    public String getName() {
        return name;
    }

    public String getLoginCredentials() {
        return loginCredentials;
    }



    public ArrayList<PointofInterest> getSavedPOI() {
        return savedPOI;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setLoginCredentials(String loginCredentials) {
        this.loginCredentials = loginCredentials;
    }

    public void setSavedPOI(ArrayList<PointofInterest> savedPOI) {
        this.savedPOI = savedPOI;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AppLayers = new javax.swing.JLayeredPane();
        LoginPage = new javax.swing.JPanel();
        Login = new javax.swing.JButton();
        UserID = new javax.swing.JTextField();
        Pass = new javax.swing.JTextField();
        try{

            BufferedImage image = ImageIO.read(new File("./logoImage.jpg"));
            jLabel1 = new JLabel(new ImageIcon(image));
            Buildings = new javax.swing.JPanel();
            dropDownMenu = new javax.swing.JComboBox<>();
            try{

                BufferedImage image1 = ImageIO.read(new File("./logoImage.jpg"));
                jLabel2 = new JLabel(new ImageIcon(image1));
                try{

                    BufferedImage image2 = ImageIO.read(new File("./AH_image.jpg"));
                    jLabel3 = new JLabel(new ImageIcon(image2));
                    try{

                        BufferedImage image3 = ImageIO.read(new File("./MC_image.jpg"));
                        jLabel4 = new JLabel(new ImageIcon(image3));
                        try{

                            BufferedImage image4 = ImageIO.read(new File("./AR_image.jpg"));
                            jLabel5 = new JLabel(new ImageIcon(image4);

                                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                                AppLayers.setLayout(new java.awt.CardLayout());

                                Login.setText("Login");
                                Login.addActionListener(new java.awt.event.ActionListener() {
                                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        LoginActionPerformed(evt);
                                    }
                                });

                                UserID.setText("User");
                                UserID.addActionListener(new java.awt.event.ActionListener() {
                                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        UserIDActionPerformed(evt);
                                    }
                                });

                                Pass.setText("Pass");

                            }catch(IOException exception){
                                System.out.println("error.");
                            }
                            jLabel1.setText("Logo of Uwo");

                            javax.swing.GroupLayout LoginPageLayout = new javax.swing.GroupLayout(LoginPage);
                            LoginPage.setLayout(LoginPageLayout);
                            LoginPageLayout.setHorizontalGroup(
                                LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(LoginPageLayout.createSequentialGroup()
                                    .addGap(234, 234, 234)
                                    .addGroup(LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Pass)
                                        .addComponent(Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(UserID))
                                    .addContainerGap(243, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPageLayout.createSequentialGroup()
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1)
                                    .addGap(85, 85, 85))
                            );
                            LoginPageLayout.setVerticalGroup(
                                LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPageLayout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(UserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                                    .addComponent(Login)
                                    .addGap(76, 76, 76))
                            );

                            AppLayers.add(LoginPage, "card2");

                            dropDownMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Middlesex College", "Almuni Hall", "Advanced Facility for Avian Research"}));
                            dropDownMenu.addActionListener(new java.awt.event.ActionListener() {
                                public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    dropDownMenuActionPerformed(evt);
                                }
                            });

                        }catch(IOException exception){
                            System.out.println("error.");
                        }
                        jLabel2.setText("Logo Of Uwo");

                    }catch(IOException exception){
                        System.out.println("error.");
                    }
                    jLabel3.setText("Alumni Hall");

                }catch(IOException exception){
                    System.out.println("error.");
                }
                jLabel4.setText("Middlesex College");

            }catch(IOException exception){
                System.out.println("error.");
            }
            jLabel5.setText("Advanced Facility for Avian Research");

            javax.swing.GroupLayout BuildingsLayout = new javax.swing.GroupLayout(Buildings);
            Buildings.setLayout(BuildingsLayout);
            BuildingsLayout.setHorizontalGroup(
                BuildingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BuildingsLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(34, 34, 34))
                .addGroup(BuildingsLayout.createSequentialGroup()
                    .addGap(183, 183, 183)
                    .addComponent(dropDownMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(BuildingsLayout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(105, 105, 105)
                    .addComponent(jLabel5)
                    .addGap(64, 64, 64))
            );
            BuildingsLayout.setVerticalGroup(
                BuildingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BuildingsLayout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(jLabel2)
                    .addGap(68, 68, 68)
                    .addComponent(dropDownMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                    .addGroup(BuildingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5))
                    .addGap(24, 24, 24))
            );

            AppLayers.add(Buildings, "card3");

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AppLayers)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AppLayers, javax.swing.GroupLayout.Alignment.TRAILING)
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents
    
    
    /*
    Method for the login button, when the user enters the correct login 
    credentials, the JFrame will switch from the login panel to the Buildings 
    Panel where the user can choose the building they would like to save POI's
    for.
    */
    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
        JSONParser userInfo = new JSONParser();
        
        User newUser = new User();
        
        try{
            
            FileReader openLogin;
            openLogin = new FileReader("loginInfo.json");
            System.out.println("success\n"); // to test that the JSON file opened successfully
            Object obj =  userInfo.parse(openLogin);
            JSONArray arr = (JSONArray)obj;
            JSONObject jsonobj = (JSONObject)arr.get(0); // get the username and password stored at index 0 in the login JSON file
                        
            String userID = UserID.getText();
            String pass = Pass.getText();
            
            if(userID.equals(jsonobj.get("name")) == true && pass.equals(jsonobj.get("loginCredentials")) == true){
                switchPanels(Buildings);
                JOptionPane.showMessageDialog(null,"Access Granted. Welcome " + userID);
                newUser.setName(userID);
                newUser.setLoginCredentials(pass);
                
            }else{
                JOptionPane.showMessageDialog(null,"Incorrect User/Password!");
            
            }
         
            
            openLogin.close();
            
        }catch (FileNotFoundException ae){
            
            System.out.println("FileNotFound\n");
            
        }catch(IOException se){
            
           System.out.println("ErrorClosingFile\n");
           
        }catch(ParseException de){
            
           System.out.println("ErrorParsing\n");
           
        }
    }//GEN-LAST:event_LoginActionPerformed

    private void UserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserIDActionPerformed

    private void dropDownMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropDownMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropDownMenuActionPerformed
    
    public void displayLogo(){
        LoginPage.add(jLabel1);
        Buildings.add(jLabel2);
    }
    
    public void displayBuildings(){
        Buildings.add(jLabel3);
        Buildings.add(jLabel4);
        Buildings.add(jLabel5);
    }
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }
    
    
    /*
    switchPanels method will switch between panels provided the user enters the 
    appropriate input. (i.e. for the login page, if the user enters the correct
    login credentials they will be redirected to the buildings page).
    */
    public void switchPanels(JPanel panel){
        AppLayers.removeAll();
        AppLayers.add(panel);
        AppLayers.repaint();
        AppLayers.revalidate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane AppLayers;
    private javax.swing.JPanel Buildings;
    private javax.swing.JButton Login;
    private javax.swing.JPanel LoginPage;
    private javax.swing.JTextField Pass;
    private javax.swing.JTextField UserID;
    private javax.swing.JComboBox<String> dropDownMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
